# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2d3a7a9b14af12373586db509e6eee2d1e37aaaa2ae59faa59788959423a3c0ded14c84f7a6cdc336f1f69e96e5072663d24a385956369b1ed262ebd7d413443

test:
  secret_key_base: 6bc0213981696fc6831403b2e66633afa5b7cbbdb1de698ac2544be45e4cc88adba02a77b16560531ebec8b08fc6382db9e23a807c32ece89bc441604bde2f54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
